# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fileupload_pb2 as fileupload__pb2


class FileUploadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
            "/FileUpload/UploadFile",
            request_serializer=fileupload__pb2.IncomingFile.SerializeToString,
            response_deserializer=fileupload__pb2.ReturnValue.FromString,
        )


class FileUploadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FileUploadServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UploadFile": grpc.unary_unary_rpc_method_handler(
            servicer.UploadFile,
            request_deserializer=fileupload__pb2.IncomingFile.FromString,
            response_serializer=fileupload__pb2.ReturnValue.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "FileUpload", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class FileUpload(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/FileUpload/UploadFile",
            fileupload__pb2.IncomingFile.SerializeToString,
            fileupload__pb2.ReturnValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
