# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileupload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileupload.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x66ileupload.proto\"\x1f\n\x0cIncomingFile\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bReturnValue\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\nFileUpload\x12+\n\nUploadFile\x12\r.IncomingFile\x1a\x0c.ReturnValue\"\x00\x62\x06proto3'
)




_INCOMINGFILE = _descriptor.Descriptor(
  name='IncomingFile',
  full_name='IncomingFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='IncomingFile.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=51,
)


_RETURNVALUE = _descriptor.Descriptor(
  name='ReturnValue',
  full_name='ReturnValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ReturnValue.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['IncomingFile'] = _INCOMINGFILE
DESCRIPTOR.message_types_by_name['ReturnValue'] = _RETURNVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IncomingFile = _reflection.GeneratedProtocolMessageType('IncomingFile', (_message.Message,), {
  'DESCRIPTOR' : _INCOMINGFILE,
  '__module__' : 'fileupload_pb2'
  # @@protoc_insertion_point(class_scope:IncomingFile)
  })
_sym_db.RegisterMessage(IncomingFile)

ReturnValue = _reflection.GeneratedProtocolMessageType('ReturnValue', (_message.Message,), {
  'DESCRIPTOR' : _RETURNVALUE,
  '__module__' : 'fileupload_pb2'
  # @@protoc_insertion_point(class_scope:ReturnValue)
  })
_sym_db.RegisterMessage(ReturnValue)



_FILEUPLOAD = _descriptor.ServiceDescriptor(
  name='FileUpload',
  full_name='FileUpload',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=85,
  serialized_end=142,
  methods=[
  _descriptor.MethodDescriptor(
    name='UploadFile',
    full_name='FileUpload.UploadFile',
    index=0,
    containing_service=None,
    input_type=_INCOMINGFILE,
    output_type=_RETURNVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILEUPLOAD)

DESCRIPTOR.services_by_name['FileUpload'] = _FILEUPLOAD

# @@protoc_insertion_point(module_scope)
